// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-OqGTVwsBou6KTWEUqnprMJtsIi9GLPU',
    appId: '1:952643607444:web:b23f4248cf9ed09d210d81',
    messagingSenderId: '952643607444',
    projectId: 'w-health-4c125',
    authDomain: 'w-health-4c125.firebaseapp.com',
    storageBucket: 'w-health-4c125.appspot.com',
    measurementId: 'G-Q75JKB08BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ahcoGJaM7vrma7rS5EWrWZHDjPLY34Q',
    appId: '1:952643607444:android:2331907e4a11de69210d81',
    messagingSenderId: '952643607444',
    projectId: 'w-health-4c125',
    storageBucket: 'w-health-4c125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk2KBmK5klDQMCsfX_9cEEehaCJPpe0yE',
    appId: '1:952643607444:ios:e88ab9896f8d8215210d81',
    messagingSenderId: '952643607444',
    projectId: 'w-health-4c125',
    storageBucket: 'w-health-4c125.appspot.com',
    iosBundleId: 'com.example.wHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk2KBmK5klDQMCsfX_9cEEehaCJPpe0yE',
    appId: '1:952643607444:ios:e88ab9896f8d8215210d81',
    messagingSenderId: '952643607444',
    projectId: 'w-health-4c125',
    storageBucket: 'w-health-4c125.appspot.com',
    iosBundleId: 'com.example.wHealth',
  );
}
